### ISSUE TITLE
Option to discard trailing Zeros

### ISSUE THREAD

**Issue by Tuen2000** [9-FS/scaler#1]
Add an Option to the Formatter to discard trailing zeros.
May be with an option to keep n zeros.

**Comment by 9-FS** [comment]
I don't see the usecase in being able to keep a customisable amount of n trailing zeros. I think it would do more harm than good to have that.

Added ability to remove trailing zeros altogether in version 1.2.0. with `Formatter::set_trailing_zeros(false)`.
